GET http://localhost:3001/api/ping

###
GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
content-type:application/json

{
  "name":"Aishat Tolu",
  "dateOfBirth": "2000-07-02",
  "ssn": "090786-122X",
  "gender": "male",
  "occupation": "New york city cop"
}